// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY4ETg03EXNiDyHIe_wdS80SjBQM-E-18',
    appId: '1:121337473711:web:1943168a8e2b7c561a425a',
    messagingSenderId: '121337473711',
    projectId: 'kkradvanced2025',
    authDomain: 'kkradvanced2025.firebaseapp.com',
    storageBucket: 'kkradvanced2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJcFkGNtZKdxbw8IY-DxrJSjqfC0wRhMI',
    appId: '1:121337473711:android:22311ed7fd2226b01a425a',
    messagingSenderId: '121337473711',
    projectId: 'kkradvanced2025',
    storageBucket: 'kkradvanced2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjuZATSCdu-apH99m0PSHg-uD2gaGPJY',
    appId: '1:121337473711:ios:3cf0f14eab16836a1a425a',
    messagingSenderId: '121337473711',
    projectId: 'kkradvanced2025',
    storageBucket: 'kkradvanced2025.firebasestorage.app',
    iosBundleId: 'com.kkr.flutteradvanced2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjuZATSCdu-apH99m0PSHg-uD2gaGPJY',
    appId: '1:121337473711:ios:34920dfd520b2ff41a425a',
    messagingSenderId: '121337473711',
    projectId: 'kkradvanced2025',
    storageBucket: 'kkradvanced2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanced2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY4ETg03EXNiDyHIe_wdS80SjBQM-E-18',
    appId: '1:121337473711:web:da5b0c58d89e232f1a425a',
    messagingSenderId: '121337473711',
    projectId: 'kkradvanced2025',
    authDomain: 'kkradvanced2025.firebaseapp.com',
    storageBucket: 'kkradvanced2025.firebasestorage.app',
  );
}
